
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AnA
 */
public class UIBuilder extends javax.swing.JFrame {

    /**
     * Creates new form UIBuilder
     */
    public UIBuilder() {
        initComponents();
        isSpecialityPanel1.setVisible(false);
    }

    FillingInfo doctorFiller = new DentistDoctorFiller();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        PersonaljPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameTextField1 = new javax.swing.JTextField();
        lastNameTextField2 = new javax.swing.JTextField();
        emailTextField3 = new javax.swing.JTextField();
        phoneTextField4 = new javax.swing.JTextField();
        websiteTextField5 = new javax.swing.JTextField();
        BiographyjPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        licenceCountryTextField6 = new javax.swing.JTextField();
        licenceNumberTextField7 = new javax.swing.JTextField();
        yearsInPracticeTextField8 = new javax.swing.JTextField();
        genderComboBox1 = new javax.swing.JComboBox<>();
        EducationjPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        degreeTextField9 = new javax.swing.JTextField();
        majorTextField10 = new javax.swing.JTextField();
        schoolTextField11 = new javax.swing.JTextField();
        yearEduTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        addMoreEducationButton2 = new javax.swing.JButton();
        AddressjPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        countryTextField13 = new javax.swing.JTextField();
        cityTextField14 = new javax.swing.JTextField();
        stateTextField15 = new javax.swing.JTextField();
        postalCodeTextField16 = new javax.swing.JTextField();
        addMoreAddressButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        streetCodeTextField17 = new javax.swing.JTextField();
        SpecialityPanel1 = new javax.swing.JPanel();
        isSpecialistCheckBox1 = new javax.swing.JCheckBox();
        isSpecialityPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        specializationTextField1 = new javax.swing.JTextField();
        specializationYearTextField2 = new javax.swing.JTextField();
        addMoreSpecialityButton3 = new javax.swing.JButton();
        addDoctorButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portal Form");
        setAlwaysOnTop(true);

        PersonaljPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Info"));

        jLabel1.setText("First Name");

        jLabel2.setText("Email Address");

        jLabel3.setText("Website");

        jLabel4.setText("Last Name");

        jLabel5.setText("Phone");

        phoneTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PersonaljPanelLayout = new javax.swing.GroupLayout(PersonaljPanel);
        PersonaljPanel.setLayout(PersonaljPanelLayout);
        PersonaljPanelLayout.setHorizontalGroup(
            PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonaljPanelLayout.createSequentialGroup()
                        .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameTextField1)
                            .addComponent(emailTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNameTextField2)
                            .addComponent(phoneTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addComponent(websiteTextField5))
                .addGap(37, 37, 37))
        );
        PersonaljPanelLayout.setVerticalGroup(
            PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lastNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(emailTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(websiteTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BiographyjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Biography"));

        jLabel6.setText("Licence Country");

        jLabel7.setText("Licence Number");

        jLabel8.setText("Years in Practice");

        jLabel9.setText("Gender");

        genderComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderComboBox1.setToolTipText("Gender");

        javax.swing.GroupLayout BiographyjPanelLayout = new javax.swing.GroupLayout(BiographyjPanel);
        BiographyjPanel.setLayout(BiographyjPanelLayout);
        BiographyjPanelLayout.setHorizontalGroup(
            BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiographyjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiographyjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(licenceCountryTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BiographyjPanelLayout.createSequentialGroup()
                        .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BiographyjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(BiographyjPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(yearsInPracticeTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(licenceNumberTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(genderComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        BiographyjPanelLayout.setVerticalGroup(
            BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiographyjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiographyjPanelLayout.createSequentialGroup()
                        .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(licenceCountryTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(licenceNumberTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiographyjPanelLayout.createSequentialGroup()
                        .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(genderComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGroup(BiographyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(yearsInPracticeTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EducationjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Education"));

        jLabel10.setText("Degree");

        jLabel11.setText("Major");

        jLabel12.setText("school");

        jLabel13.setText("Year");

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("note: If you have multiple degrees, enter them in \"descending\" order...");

        addMoreEducationButton2.setText("Add More");
        addMoreEducationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreEducationButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EducationjPanelLayout = new javax.swing.GroupLayout(EducationjPanel);
        EducationjPanel.setLayout(EducationjPanelLayout);
        EducationjPanelLayout.setHorizontalGroup(
            EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EducationjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationjPanelLayout.createSequentialGroup()
                        .addGroup(EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EducationjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(degreeTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EducationjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(23, 23, 23)
                                .addComponent(schoolTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EducationjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(majorTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(yearEduTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EducationjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMoreEducationButton2)
                .addGap(23, 23, 23))
        );
        EducationjPanelLayout.setVerticalGroup(
            EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EducationjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreeTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(yearEduTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(majorTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EducationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(schoolTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMoreEducationButton2)
                .addContainerGap())
        );

        AddressjPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        AddressjPanel6.setToolTipText("");

        jLabel14.setText("Country");

        jLabel15.setText("City");

        jLabel16.setText("State");

        jLabel17.setText("Postal Code");

        postalCodeTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTextField16ActionPerformed(evt);
            }
        });

        addMoreAddressButton1.setText("Add More");
        addMoreAddressButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreAddressButton1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Street");

        streetCodeTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetCodeTextField17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddressjPanel6Layout = new javax.swing.GroupLayout(AddressjPanel6);
        AddressjPanel6.setLayout(AddressjPanel6Layout);
        AddressjPanel6Layout.setHorizontalGroup(
            AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressjPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddressjPanel6Layout.createSequentialGroup()
                            .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressjPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)))
                    .addGroup(AddressjPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(45, 45, 45)))
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddressjPanel6Layout.createSequentialGroup()
                        .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(postalCodeTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(countryTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityTextField14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateTextField15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(addMoreAddressButton1))
                    .addGroup(AddressjPanel6Layout.createSequentialGroup()
                        .addComponent(streetCodeTextField17)
                        .addGap(147, 147, 147)))
                .addContainerGap())
        );
        AddressjPanel6Layout.setVerticalGroup(
            AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressjPanel6Layout.createSequentialGroup()
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(countryTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cityTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(stateTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(streetCodeTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postalCodeTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressjPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMoreAddressButton1)
                .addContainerGap())
        );

        SpecialityPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Speciality"));

        isSpecialistCheckBox1.setText("Is Specialist");
        isSpecialistCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSpecialistCheckBox1ActionPerformed(evt);
            }
        });

        isSpecialityPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setText("Area of speciallization");

        jLabel20.setText("Start Year");

        addMoreSpecialityButton3.setText("Add More");
        addMoreSpecialityButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreSpecialityButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout isSpecialityPanel1Layout = new javax.swing.GroupLayout(isSpecialityPanel1);
        isSpecialityPanel1.setLayout(isSpecialityPanel1Layout);
        isSpecialityPanel1Layout.setHorizontalGroup(
            isSpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isSpecialityPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isSpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(isSpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specializationTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specializationYearTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isSpecialityPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMoreSpecialityButton3)
                .addContainerGap())
        );
        isSpecialityPanel1Layout.setVerticalGroup(
            isSpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isSpecialityPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isSpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(specializationTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(isSpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specializationYearTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addMoreSpecialityButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SpecialityPanel1Layout = new javax.swing.GroupLayout(SpecialityPanel1);
        SpecialityPanel1.setLayout(SpecialityPanel1Layout);
        SpecialityPanel1Layout.setHorizontalGroup(
            SpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialityPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isSpecialityPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SpecialityPanel1Layout.createSequentialGroup()
                        .addComponent(isSpecialistCheckBox1)
                        .addGap(0, 403, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SpecialityPanel1Layout.setVerticalGroup(
            SpecialityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialityPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(isSpecialistCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(isSpecialityPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        addDoctorButton4.setText("Add Doctor");
        addDoctorButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpecialityPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddressjPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BiographyjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PersonaljPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EducationjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDoctorButton4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PersonaljPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BiographyjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EducationjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddressjPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SpecialityPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(addDoctorButton4)
                .addContainerGap(650, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextField4ActionPerformed

    private void addMoreAddressButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoreAddressButton1ActionPerformed
        // TODO add your handling code here:
        AddressSec addressSec = new AddressSec();
        addressSec.setCity(cityTextField14.getText());
        addressSec.setCountry(countryTextField13.getText());
        addressSec.setPostalCode(postalCodeTextField16.getText());
        addressSec.setState(stateTextField15.getText());
        addressSec.setStreet(streetCodeTextField17.getText());
        doctorFiller.setAddressSec(addressSec);

        countryTextField13.setText("");
        postalCodeTextField16.setText("");
        cityTextField14.setText("");
        streetCodeTextField17.setText("");
        stateTextField15.setText("");
    }//GEN-LAST:event_addMoreAddressButton1ActionPerformed

    private void addMoreEducationButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoreEducationButton2ActionPerformed
        // TODO add your handling code here:

        EducationInfo educationInfo = new EducationInfo();
        educationInfo.setDegree(degreeTextField9.getText());
        educationInfo.setMajor(majorTextField10.getText());
        educationInfo.setSchoolName(schoolTextField11.getText());
        educationInfo.setGraduationDate(Integer.parseInt(yearEduTextField12.getText()));
        doctorFiller.setEducationInfo(educationInfo);

        degreeTextField9.setText("");
        majorTextField10.setText("");
        schoolTextField11.setText("");
        yearEduTextField12.setText("");
    }//GEN-LAST:event_addMoreEducationButton2ActionPerformed

    private void postalCodeTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeTextField16ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_postalCodeTextField16ActionPerformed

    private void isSpecialistCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSpecialistCheckBox1ActionPerformed
        // TODO add your handling code here:
        isSpecialityPanel1.setVisible(isSpecialistCheckBox1.isSelected());
    }//GEN-LAST:event_isSpecialistCheckBox1ActionPerformed

    private void addMoreSpecialityButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoreSpecialityButton3ActionPerformed
        // TODO add your handling code here:
        SpecializationSec specializationSec = new SpecializationSec();
        specializationSec.setSpecializationArea(specializationTextField1.getText());
        specializationSec.setStartYear(Integer.parseInt(specializationYearTextField2.getText()));
        doctorFiller.setSpecializationSec(specializationSec);

        specializationTextField1.setText("");
        specializationYearTextField2.setText("");
    }//GEN-LAST:event_addMoreSpecialityButton3ActionPerformed

    private void addDoctorButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorButton4ActionPerformed
        // TODO add your handling code here:

        PersonalInfo personalInfo = new PersonalInfo();
        personalInfo.setFisrtName(firstNameTextField1.getText());
        personalInfo.setLastName(lastNameTextField2.getText());
        personalInfo.setGender(genderComboBox1.getItemAt(getState()));
        personalInfo.setContactMethods(new ContactMethods(emailTextField3.getText(), websiteTextField5.getText(), phoneTextField4.getText()));
        doctorFiller.setPersonalInfo(personalInfo);

        Biography biography = new Biography();
        biography.setLicenseCountyName(licenceCountryTextField6.getText());
        biography.setLicenseNumber(Integer.parseInt(licenceNumberTextField7.getText()));
        biography.setPracticeYears(Integer.parseInt(yearsInPracticeTextField8.getText()));
        doctorFiller.setBiography(biography);

        EducationInfo educationInfo = new EducationInfo();
        educationInfo.setDegree(degreeTextField9.getText());
        educationInfo.setMajor(majorTextField10.getText());
        educationInfo.setSchoolName(schoolTextField11.getText());
        educationInfo.setGraduationDate(Integer.parseInt(yearEduTextField12.getText()));
        doctorFiller.setEducationInfo(educationInfo);

        AddressSec addressSec = new AddressSec();
        addressSec.setCity(cityTextField14.getText());
        addressSec.setCountry(countryTextField13.getText());
        addressSec.setPostalCode(postalCodeTextField16.getText());
        addressSec.setState(stateTextField15.getText());
        addressSec.setStreet(streetCodeTextField17.getText());
        doctorFiller.setAddressSec(addressSec);

        if (isSpecialistCheckBox1.isSelected()) {
            SpecializationSec specializationSec = new SpecializationSec();
            specializationSec.setSpecializationArea(specializationTextField1.getText());
            specializationSec.setStartYear(Integer.parseInt(specializationYearTextField2.getText()));
            doctorFiller.setSpecializationSec(specializationSec);
        }
        
        this.setVisible(false);
        JOptionPane.showMessageDialog(rootPane, doctorFiller.toString());
    }//GEN-LAST:event_addDoctorButton4ActionPerformed

    private void streetCodeTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetCodeTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetCodeTextField17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIBuilder().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressjPanel6;
    private javax.swing.JPanel BiographyjPanel;
    private javax.swing.JPanel EducationjPanel;
    private javax.swing.JPanel PersonaljPanel;
    private javax.swing.JPanel SpecialityPanel1;
    private javax.swing.JButton addDoctorButton4;
    private javax.swing.JButton addMoreAddressButton1;
    private javax.swing.JButton addMoreEducationButton2;
    private javax.swing.JButton addMoreSpecialityButton3;
    private javax.swing.JTextField cityTextField14;
    private javax.swing.JTextField countryTextField13;
    private javax.swing.JTextField degreeTextField9;
    private javax.swing.JTextField emailTextField3;
    private javax.swing.JTextField firstNameTextField1;
    private javax.swing.JComboBox<String> genderComboBox1;
    private javax.swing.JCheckBox isSpecialistCheckBox1;
    private javax.swing.JPanel isSpecialityPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTextField2;
    private javax.swing.JTextField licenceCountryTextField6;
    private javax.swing.JTextField licenceNumberTextField7;
    private javax.swing.JTextField majorTextField10;
    private javax.swing.JTextField phoneTextField4;
    private javax.swing.JTextField postalCodeTextField16;
    private javax.swing.JTextField schoolTextField11;
    private javax.swing.JTextField specializationTextField1;
    private javax.swing.JTextField specializationYearTextField2;
    private javax.swing.JTextField stateTextField15;
    private javax.swing.JTextField streetCodeTextField17;
    private javax.swing.JTextField websiteTextField5;
    private javax.swing.JTextField yearEduTextField12;
    private javax.swing.JTextField yearsInPracticeTextField8;
    // End of variables declaration//GEN-END:variables
}
